# RESTBase config for Product Infrastructure!
num_workers: 0
services:
  - name: restbase
    module: hyperswitch
    conf:
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
          - path: lib/normalize_headers_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: http://localhost/w/api.php
                  forward_headers: true
                - pattern: http://localhost:8142
                  forward_headers: true
                - pattern: /^https?:\/\//
        paths:
          /{domain:en.wikipedia.org}/{api:v1}: &production_site_api_v1
            x-modules:
              - spec:
                  paths:
                    /page:
                      x-modules:
                        - path: v1/content.yaml
                        - path: v1/related.js
                        - path: v1/mobileapps.js
                          options:
                            host: https://mobileapps.wmflabs.org
                        - path: v1/summary.js
                          options:
                            host: https://mobileapps.wmflabs.org
                            implementation: mcs
                            protocol: https
                        - path: v1/css.yaml
                          options:
                            host: https://mobileapps.wmflabs.org
                        - path: v1/javascript.yaml
                          options:
                            host: https://mobileapps.wmflabs.org
                        - path: v1/i18n.yaml
                          options:
                            host: https://mobileapps.wmflabs.org
                        - path: v1/pcs/stored_endpoint.js
                          options:
                            name: media-list
                            host: https://mobileapps.wmflabs.org
                        - path: v1/pcs/stored_endpoint.js
                          options:
                            name: mobile-html
                            host: https://mobileapps.wmflabs.org
                        - path: v1/pcs/mobile-html-offline-resources.yaml
                          options:
                            host: https://mobileapps.wmflabs.org
                        - path: v1/talk.yaml
                          options:
                            host: https://mobileapps.wmflabs.org
                    /feed:
                      x-modules:
                        - path: v1/feed.js
                          options:
                            host: https://wikifeeds.wmflabs.org
                        - path: v1/announcements.yaml
                          options:
                            host: https://wikifeeds.wmflabs.org
                        - path: v1/onthisday.js
                          options:
                            host: https://wikifeeds.wmflabs.org
                    /transform:
                      x-modules:
                        - path: v1/pcs/transform.js
                          options:
                            mobileapps_host: https://mobileapps.wmflabs.org


          /{domain:en.wikipedia.org}/{api:sys}: &production_site_api_sys
            x-modules:
              - path: projects/proxy.yaml
                options:
                  backend_host_template: '{{"/{domain}/sys/legacy"}}'
              - spec:
                  paths:
                    /action:
                      x-modules:
                        - path: sys/action.js
                          options:
                            apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
                            baseUriTemplate: "{{'https://{domain}/api/rest_v1'}}"
                    /table:
                      x-modules:
                        - path: sys/table.js
                          options:
                            conf:
                              backend: sqlite
                              dbname: db.sqlite3
                              pool_idle_timeout: 20000
                              retry_delay: 250
                              retry_limit: 10
                              show_sql: false
                              storage_groups:
                                - name: local
                                  domains: /./
                    /legacy/key_value:
                      x-modules:
                        - path: sys/key_value.js
                    /legacy/page_revisions:
                      x-modules:
                        - path: sys/page_revisions.js

          /{domain:es.wikipedia.org}/{api:v1}: *production_site_api_v1
          /{domain:es.wikipedia.org}/{api:sys}: *production_site_api_sys

          # /{domain:your.domain.here}/{api:v1}: *production_site_api_v1
          # /{domain:your.domain.here}/{api:sys}: *production_site_api_sys

# Finally, a standard service-runner config.
info:
  name: restbase

logging:
  name: restbase
  level: info
